// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-ldIpqIygmNCC5ZXZUKrzPVEJq2p2K2c',
    appId: '1:310188107229:web:d7539b3a08eadf021cc234',
    messagingSenderId: '310188107229',
    projectId: 'shopping-database-620c5',
    authDomain: 'shopping-database-620c5.firebaseapp.com',
    databaseURL: 'https://shopping-database-620c5-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-database-620c5.firebasestorage.app',
    measurementId: 'G-MKSRWDB4EC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA05TXyQ1AMQ4whenf1SQFDd4eJHvzRN60',
    appId: '1:310188107229:android:0137adf7245f40c21cc234',
    messagingSenderId: '310188107229',
    projectId: 'shopping-database-620c5',
    databaseURL: 'https://shopping-database-620c5-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-database-620c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYaX6G4wNFUeJqR9UID3IcebvRQL4Lvww',
    appId: '1:310188107229:ios:ad1494bc07dd66781cc234',
    messagingSenderId: '310188107229',
    projectId: 'shopping-database-620c5',
    databaseURL: 'https://shopping-database-620c5-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-database-620c5.firebasestorage.app',
    iosBundleId: 'com.example.shoppingWebApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYaX6G4wNFUeJqR9UID3IcebvRQL4Lvww',
    appId: '1:310188107229:ios:ad1494bc07dd66781cc234',
    messagingSenderId: '310188107229',
    projectId: 'shopping-database-620c5',
    databaseURL: 'https://shopping-database-620c5-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-database-620c5.firebasestorage.app',
    iosBundleId: 'com.example.shoppingWebApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-ldIpqIygmNCC5ZXZUKrzPVEJq2p2K2c',
    appId: '1:310188107229:web:de3af3808cc984c01cc234',
    messagingSenderId: '310188107229',
    projectId: 'shopping-database-620c5',
    authDomain: 'shopping-database-620c5.firebaseapp.com',
    databaseURL: 'https://shopping-database-620c5-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-database-620c5.firebasestorage.app',
    measurementId: 'G-X6WN5MVFEB',
  );

}